
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label lblprod1;
	private global::Gtk.Label lblprod2;
	private global::Gtk.Label lblprod3;
	private global::Gtk.Entry producto1;
	private global::Gtk.Entry producto2;
	private global::Gtk.Entry producto3;
	private global::Gtk.Entry total;
	private global::Gtk.Entry iva;
	private global::Gtk.Entry subtotal;
	private global::Gtk.Label lblsubtotal;
	private global::Gtk.Label lbliva;
	private global::Gtk.Label lbltotal;
	private global::Gtk.Button facturar;
	private global::Gtk.Button limpiar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblprod1 = new global::Gtk.Label ();
		this.lblprod1.Name = "lblprod1";
		this.lblprod1.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 1");
		this.fixed1.Add (this.lblprod1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblprod1]));
		w1.X = 27;
		w1.Y = 16;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblprod2 = new global::Gtk.Label ();
		this.lblprod2.Name = "lblprod2";
		this.lblprod2.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 2");
		this.fixed1.Add (this.lblprod2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblprod2]));
		w2.X = 26;
		w2.Y = 52;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblprod3 = new global::Gtk.Label ();
		this.lblprod3.Name = "lblprod3";
		this.lblprod3.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 3");
		this.fixed1.Add (this.lblprod3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblprod3]));
		w3.X = 27;
		w3.Y = 87;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.producto1 = new global::Gtk.Entry ();
		this.producto1.CanFocus = true;
		this.producto1.Name = "producto1";
		this.producto1.IsEditable = true;
		this.producto1.InvisibleChar = '●';
		this.fixed1.Add (this.producto1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.producto1]));
		w4.X = 165;
		w4.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.producto2 = new global::Gtk.Entry ();
		this.producto2.CanFocus = true;
		this.producto2.Name = "producto2";
		this.producto2.IsEditable = true;
		this.producto2.InvisibleChar = '●';
		this.fixed1.Add (this.producto2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.producto2]));
		w5.X = 166;
		w5.Y = 45;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.producto3 = new global::Gtk.Entry ();
		this.producto3.CanFocus = true;
		this.producto3.Name = "producto3";
		this.producto3.IsEditable = true;
		this.producto3.InvisibleChar = '●';
		this.fixed1.Add (this.producto3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.producto3]));
		w6.X = 166;
		w6.Y = 81;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.total = new global::Gtk.Entry ();
		this.total.CanFocus = true;
		this.total.Name = "total";
		this.total.IsEditable = true;
		this.total.InvisibleChar = '●';
		this.fixed1.Add (this.total);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.total]));
		w7.X = 168;
		w7.Y = 221;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.iva = new global::Gtk.Entry ();
		this.iva.CanFocus = true;
		this.iva.Name = "iva";
		this.iva.IsEditable = true;
		this.iva.InvisibleChar = '●';
		this.fixed1.Add (this.iva);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.iva]));
		w8.X = 167;
		w8.Y = 186;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.subtotal = new global::Gtk.Entry ();
		this.subtotal.CanFocus = true;
		this.subtotal.Name = "subtotal";
		this.subtotal.IsEditable = true;
		this.subtotal.InvisibleChar = '●';
		this.fixed1.Add (this.subtotal);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.subtotal]));
		w9.X = 167;
		w9.Y = 152;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblsubtotal = new global::Gtk.Label ();
		this.lblsubtotal.Name = "lblsubtotal";
		this.lblsubtotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Subtotal");
		this.fixed1.Add (this.lblsubtotal);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblsubtotal]));
		w10.X = 33;
		w10.Y = 157;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbliva = new global::Gtk.Label ();
		this.lbliva.Name = "lbliva";
		this.lbliva.LabelProp = global::Mono.Unix.Catalog.GetString ("IVA");
		this.fixed1.Add (this.lbliva);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbliva]));
		w11.X = 51;
		w11.Y = 192;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lbltotal = new global::Gtk.Label ();
		this.lbltotal.Name = "lbltotal";
		this.lbltotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Total");
		this.fixed1.Add (this.lbltotal);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lbltotal]));
		w12.X = 44;
		w12.Y = 225;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.facturar = new global::Gtk.Button ();
		this.facturar.CanFocus = true;
		this.facturar.Name = "facturar";
		this.facturar.UseUnderline = true;
		this.facturar.Label = global::Mono.Unix.Catalog.GetString ("Facturar");
		this.fixed1.Add (this.facturar);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.facturar]));
		w13.X = 88;
		w13.Y = 286;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.limpiar = new global::Gtk.Button ();
		this.limpiar.CanFocus = true;
		this.limpiar.Name = "limpiar";
		this.limpiar.UseUnderline = true;
		this.limpiar.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
		this.fixed1.Add (this.limpiar);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.limpiar]));
		w14.X = 172;
		w14.Y = 285;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 370;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.facturar.Clicked += new global::System.EventHandler (this.OnFacturarClicked);
		this.limpiar.Clicked += new global::System.EventHandler (this.OnLimpiarClicked);
	}
}
